import type {
  CollectorRunRow,
  OperationalSnapshotRow,
  SourceObservationRow,
  SourceRef,
} from "./types.ts";

export const OPERATIONAL_NOW = "2026-08-20T12:00:00.000Z";

const FRESH = "FRESH" as const;

function src(system: string, kind: string, locator: string): SourceRef {
  return { system, kind, locator };
}

function run(
  partial: Omit<CollectorRunRow, "read_only" | "observations_emitted" | "error_code" | "error_message"> &
    Partial<Pick<CollectorRunRow, "observations_emitted" | "error_code" | "error_message">>,
): CollectorRunRow {
  return {
    read_only: true,
    observations_emitted: partial.observations_emitted ?? 1,
    error_code: partial.error_code ?? null,
    error_message: partial.error_message ?? null,
    ...partial,
  };
}

export function representativeCollectorRuns(): CollectorRunRow[] {
  return [
    run({
      id: "cc:collector-run:warmbly-company",
      collector_name: "warmbly-commercial",
      scope: "commercial",
      status: "succeeded",
      started_at: "2026-08-20T11:49:00.000Z",
      finished_at: "2026-08-20T11:50:00.000Z",
      idempotency_key: "warmbly:commercial:2026-08-20T11:50:00.000Z",
      source: src("warmbly", "crm-read-model", "commercial/pipeline"),
      observed_at: "2026-08-20T11:50:00.000Z",
      freshness_status: FRESH,
      confidence: 0.84,
    }),
    run({
      id: "cc:collector-run:asaas-company",
      collector_name: "asaas-finance",
      scope: "finance",
      status: "succeeded",
      started_at: "2026-08-20T11:39:00.000Z",
      finished_at: "2026-08-20T11:40:00.000Z",
      idempotency_key: "asaas:finance:2026-08-20T11:40:00.000Z",
      source: src("asaas", "receivable-read", "finance/receivables"),
      observed_at: "2026-08-20T11:40:00.000Z",
      freshness_status: FRESH,
      confidence: 0.9,
    }),
    run({
      id: "cc:collector-run:github-gov",
      collector_name: "github-engineering",
      scope: "repo:Governance",
      status: "succeeded",
      started_at: "2026-08-20T11:29:00.000Z",
      finished_at: "2026-08-20T11:30:00.000Z",
      idempotency_key: "github:repo:Governance:2026-08-20T11:30:00.000Z",
      source: src("github", "repo-read", "repos/Governance"),
      observed_at: "2026-08-20T11:30:00.000Z",
      freshness_status: FRESH,
      confidence: 0.95,
    }),
    run({
      id: "cc:collector-run:github-warmbly",
      collector_name: "github-engineering",
      scope: "repo:Warmbly",
      status: "succeeded",
      started_at: "2026-08-20T11:29:00.000Z",
      finished_at: "2026-08-20T11:30:00.000Z",
      idempotency_key: "github:repo:Warmbly:2026-08-20T11:30:00.000Z",
      source: src("github", "repo-read", "repos/Warmbly"),
      observed_at: "2026-08-20T11:30:00.000Z",
      freshness_status: FRESH,
      confidence: 0.95,
    }),
    run({
      id: "cc:collector-run:infra",
      collector_name: "infra-health",
      scope: "infrastructure",
      status: "succeeded",
      started_at: "2026-08-20T11:19:00.000Z",
      finished_at: "2026-08-20T11:20:00.000Z",
      idempotency_key: "infra:hosts:2026-08-20T11:20:00.000Z",
      source: src("collector", "host-health", "infrastructure/hosts"),
      observed_at: "2026-08-20T11:20:00.000Z",
      freshness_status: FRESH,
      confidence: 0.88,
    }),
    run({
      id: "cc:collector-run:pncp",
      collector_name: "pncp-freshness",
      scope: "infrastructure",
      status: "succeeded",
      started_at: "2026-08-20T11:09:00.000Z",
      finished_at: "2026-08-20T11:10:00.000Z",
      idempotency_key: "pncp:contracts:2026-08-20T11:10:00.000Z",
      source: src("extra-cli", "pncp-contract-freshness", "pncp/contracts"),
      observed_at: "2026-08-20T11:10:00.000Z",
      freshness_status: FRESH,
      confidence: 0.7,
    }),
    run({
      id: "cc:collector-run:clients",
      collector_name: "clients-ops",
      scope: "clients",
      status: "succeeded",
      started_at: "2026-08-20T11:44:00.000Z",
      finished_at: "2026-08-20T11:45:00.000Z",
      idempotency_key: "clients:ops:2026-08-20T11:45:00.000Z",
      source: src("warmbly", "client-ops", "clients/roll-up"),
      observed_at: "2026-08-20T11:45:00.000Z",
      freshness_status: FRESH,
      confidence: 0.8,
    }),
  ];
}

export function representativeSourceObservations(): SourceObservationRow[] {
  return [
    {
      id: "cc:source-observation:asaas-charges",
      scope: "finance",
      observation_kind: "charge-list",
      source: src("asaas", "charge-list", "finance/charges"),
      observed_at: "2026-08-20T11:40:00.000Z",
      freshness_status: FRESH,
      confidence: 0.9,
      collected_at: "2026-08-20T11:40:05.000Z",
      idempotency_key: "asaas:charges:2026-08-20T11:40:00.000Z",
      payload: {
        confirmed_cents: 1000000,
        received_cents: 1500000,
        paid_cents: 2500000,
      },
      error_code: null,
      error_message: null,
    },
    {
      id: "cc:source-observation:warmbly-pipeline",
      scope: "commercial",
      observation_kind: "pipeline",
      source: src("warmbly", "crm-read-model", "commercial/pipeline"),
      observed_at: "2026-08-20T11:50:00.000Z",
      freshness_status: FRESH,
      confidence: 0.84,
      collected_at: "2026-08-20T11:50:02.000Z",
      idempotency_key: "warmbly:pipeline:2026-08-20T11:50:00.000Z",
      payload: { pipeline_open_count: 4, stalled_count: 1 },
      error_code: null,
      error_message: null,
    },
    {
      id: "cc:source-observation:github-governance",
      scope: "repo:Governance",
      observation_kind: "repo-health",
      source: src("github", "repo-read", "repos/Governance"),
      observed_at: "2026-08-20T11:30:00.000Z",
      freshness_status: FRESH,
      confidence: 0.95,
      collected_at: "2026-08-20T11:30:01.000Z",
      idempotency_key: "github:Governance:2026-08-20T11:30:00.000Z",
      payload: { open_incident_count: 1, open_pr_count: 2 },
      error_code: null,
      error_message: null,
    },
    {
      id: "cc:source-observation:github-warmbly-sibling",
      scope: "repo:Warmbly",
      observation_kind: "repo-health",
      source: src("github", "repo-read", "repos/Warmbly"),
      observed_at: "2026-08-20T11:30:00.000Z",
      freshness_status: FRESH,
      confidence: 0.95,
      collected_at: "2026-08-20T11:30:01.000Z",
      idempotency_key: "github:Warmbly:2026-08-20T11:30:00.000Z",
      payload: { sibling_only: true },
      error_code: null,
      error_message: null,
    },
    {
      id: "cc:source-observation:client-acme",
      scope: "client:acme",
      observation_kind: "client-ops",
      source: src("warmbly", "client-ops", "clients/acme"),
      observed_at: "2026-08-20T11:45:00.000Z",
      freshness_status: FRESH,
      confidence: 0.8,
      collected_at: "2026-08-20T11:45:01.000Z",
      idempotency_key: "clients:acme:2026-08-20T11:45:00.000Z",
      payload: { client_slug: "acme", lifecycle: "active" },
      error_code: null,
      error_message: null,
    },
    {
      id: "cc:source-observation:client-other",
      scope: "client:other",
      observation_kind: "client-ops",
      source: src("warmbly", "client-ops", "clients/other"),
      observed_at: "2026-08-20T11:45:00.000Z",
      freshness_status: FRESH,
      confidence: 0.8,
      collected_at: "2026-08-20T11:45:01.000Z",
      idempotency_key: "clients:other:2026-08-20T11:45:00.000Z",
      payload: { client_slug: "other", lifecycle: "churn_risk" },
      error_code: null,
      error_message: null,
    },
  ];
}

export function representativeOperationalSnapshots(): OperationalSnapshotRow[] {
  return [
    {
      id: "cc:operational-snapshot:commercial-company",
      scope: "commercial",
      snapshot_kind: "commercial",
      generated_at: "2026-08-20T11:50:00.000Z",
      source: src("warmbly", "crm-read-model", "commercial/pipeline"),
      observed_at: "2026-08-20T11:50:00.000Z",
      freshness_status: FRESH,
      confidence: 0.84,
      payload: {
        schema_version: "control-center.commercial-snapshot.v1",
        funnel: { new_leads: 6, qualified: 4, opportunities: 3, proposals: 2, clients: 1 },
        pipeline_nominal: { amount_cents: 4800000, currency: "BRL" },
        pipeline_weighted: { amount_cents: 2100000, currency: "BRL", probability_reliable: true },
        aging_count: 1,
        stalled_count: 1,
        missing_next_action_count: 2,
        pipeline_open_count: 4,
        inbound_unread_count: 3,
        at_risk_client_count: 1,
        operations: {
          dispatch: {
            state: "PAUSED",
            observed: true,
            queued_approved: 140,
            sent_today: 20,
            daily_limit: 30,
            transport_health: "PAUSED_BY_KILL_SWITCH",
            slots_next_24h: 30,
            slots_next_7d: 210,
            provider_errors: 0,
          },
          delegated_first_touch: {
            policy_version: "CFG-FIRST-TOUCH-ROUTING-v1",
            runtime_release_sha: "8a2eb1f012345678901234567890123456789012",
            source_run_id: "extra-run-e2e-2026-08-20",
            queued_readback: 140,
            human_approved: 0,
            counts: { PREPARED: 180, QUEUED: 140, SENT: 20, HOLD: 1 },
            items: [{
              state: "QUEUED",
              source_run_id: "extra-run-e2e-2026-08-20",
              runtime_release_sha: "8a2eb1f012345678901234567890123456789012",
              due_at: "2026-08-27T17:30:00.000Z",
            }],
          },
          working_overview: {
            reservoir_monitored: 1200,
            actionable_now: 1200,
            needs_contact: 1019,
            needs_review: 1,
            approved_scheduled: 140,
            watch_awaiting: 20,
            suppressed: 50,
            stale_context: 12,
            due_next_24h: 30,
            theoretical_slots_24h: 90,
            slots_next_24h: 30,
            slots_next_7d: 210,
            feed_age_seconds: 300,
            replenishment_state: "WAITING_FOR_EXTRA_CLI_REFRESH",
            stale_retired: 12,
            queue_fill_blocker: "WAITING_FOR_ELIGIBLE_BATCH",
          },
          outbound_outcomes: {
            attempted: 24,
            sent: 20,
            provider_accepted: 22,
            delivered: 18,
            replies: 3,
            bounces: 1,
            complaints: 0,
            suppressed: 50,
            provider_errors: 0,
          },
          mailbox_health: { healthy: 5, blocked: 1, unknown: 0 },
          // One grouped exception row carries two occurrence ids. The list
          // total counts searchable rows, not the occurrences inside a group,
          // so the complete fixture truth is HEALTHY rather than partial.
          overview: { activity: 1, exceptions: 1, pipeline: 1 },
          activity: [
            {
              source_id: "lead-fixture-aurora",
              canonical_id: "cc:commercial-activity:lead-fixture-aurora",
              lead_or_account: "Metalúrgica Aurora",
              event: "inbound_message",
              state: "open",
              triage_state: "unread",
              conditions: ["unread", "unassigned"],
              at: "2026-08-20T11:35:00.000Z",
              age_seconds: 900,
              source: "warmbly",
              owner: null,
              priority: "high",
              next_action: "abrir o detalhe e responder à dúvida de escopo",
              evidence: "Mensagem recebida sem leitura e sem responsável.",
            },
          ],
          pipeline: [
            {
              id: "deal-fixture-aurora",
              source_id: "deal-fixture-aurora",
              company: "Metalúrgica Aurora",
              stage: "qualification",
              state: "open",
              next_action: "validar aderência ao diagnóstico",
              updated_at: "2026-08-20T11:30:00.000Z",
            },
          ],
          exceptions: [
            {
              id: "exception-fixture-owner",
              canonical_id: "cc:commercial-exception:fixture-owner",
              source_id: "lead-fixture-aurora",
              kind: "missing_owner",
              status: "open",
              workflow_state: "new",
              why: "Lead recebido sem responsável definido",
              owner: null,
              observed_at: "2026-08-20T11:35:00.000Z",
              age_seconds: 900,
              impact: "A resposta pode perder o prazo operacional.",
              recommended_next_action: "atribuir responsável e registrar o plano de tratamento",
              resolution_kind: "unsupported",
              occurrence_count: 2,
              occurrence_ids: ["owner-gap-1", "owner-gap-2"],
              sync_status: "observed",
              source: "warmbly",
              priority: "high",
            },
          ],
        },
      },
    },
    {
      id: "cc:operational-snapshot:finance-company",
      scope: "finance",
      snapshot_kind: "finance",
      generated_at: "2026-08-20T11:40:00.000Z",
      source: src("asaas", "receivable-read", "finance/receivables"),
      observed_at: "2026-08-20T11:40:00.000Z",
      freshness_status: FRESH,
      confidence: 0.9,
      payload: {
        schema_version: "control-center.finance-snapshot.v1",
        read_model_only: true,
        provider_mutations: "forbidden",
        contracted: { amount_cents: 5000000, currency: "BRL" },
        billed: { amount_cents: 4000000, currency: "BRL" },
        paid: { amount_cents: 2500000, currency: "BRL" },
        effectively_received: { amount_cents: 2500000, currency: "BRL" },
        confirmed_cents: 1000000,
        received_cents: 1500000,
        overdue: { amount_cents: 1500000, currency: "BRL" },
        receivable: { amount_cents: 2500000, currency: "BRL" },
      },
    },
    {
      id: "cc:operational-snapshot:clients-company",
      scope: "clients",
      snapshot_kind: "clients",
      generated_at: "2026-08-20T11:45:00.000Z",
      source: src("warmbly", "client-ops", "clients/roll-up"),
      observed_at: "2026-08-20T11:45:00.000Z",
      freshness_status: FRESH,
      confidence: 0.8,
      payload: {
        schema_version: "control-center.clients-snapshot.v1",
        at_risk_client_count: 1,
        open_blocker_count: 1,
      },
    },
    {
      id: "cc:operational-snapshot:engineering-company",
      scope: "company",
      snapshot_kind: "engineering",
      generated_at: "2026-08-20T11:30:00.000Z",
      source: src("github", "repo-read", "engineering/company"),
      observed_at: "2026-08-20T11:30:00.000Z",
      freshness_status: FRESH,
      confidence: 0.95,
      payload: {
        schema_version: "control-center.engineering-snapshot.v1",
        open_pr_count: 3,
        failing_check_count: 0,
        open_incident_count: 1,
      },
    },
    {
      id: "cc:operational-snapshot:engineering-governance",
      scope: "repo:Governance",
      snapshot_kind: "engineering",
      generated_at: "2026-08-20T11:30:00.000Z",
      source: src("github", "repo-read", "repos/Governance"),
      observed_at: "2026-08-20T11:30:00.000Z",
      freshness_status: FRESH,
      confidence: 0.95,
      payload: {
        schema_version: "control-center.engineering-snapshot.v1",
        open_pr_count: 2,
        failing_check_count: 1,
        open_incident_count: 1,
        repo_scopes: ["repo:Governance"],
      },
    },
    {
      id: "cc:operational-snapshot:engineering-warmbly",
      scope: "repo:Warmbly",
      snapshot_kind: "engineering",
      generated_at: "2026-08-20T11:30:00.000Z",
      source: src("github", "repo-read", "repos/Warmbly"),
      observed_at: "2026-08-20T11:30:00.000Z",
      freshness_status: FRESH,
      confidence: 0.95,
      payload: {
        schema_version: "control-center.engineering-snapshot.v1",
        open_pr_count: 9,
        failing_check_count: 9,
        open_incident_count: 9,
        sibling_marker: "repo-warmbly-only",
      },
    },
    {
      id: "cc:operational-snapshot:infrastructure",
      scope: "infrastructure",
      snapshot_kind: "infrastructure",
      generated_at: "2026-08-20T11:20:00.000Z",
      source: src("collector", "host-health", "infrastructure/hosts"),
      observed_at: "2026-08-20T11:20:00.000Z",
      freshness_status: FRESH,
      confidence: 0.88,
      payload: {
        schema_version: "control-center.infrastructure-snapshot.v1",
        status: "down",
        service_name: "edge",
      },
    },
    {
      id: "cc:operational-snapshot:pncp",
      scope: "infrastructure",
      snapshot_kind: "pncp",
      generated_at: "2026-08-20T11:10:00.000Z",
      source: src("extra-cli", "pncp-contract-freshness", "pncp/contracts"),
      observed_at: "2026-08-20T11:10:00.000Z",
      freshness_status: FRESH,
      confidence: 0.7,
      payload: {
        schema_version: "control-center.pncp-snapshot.v1",
        service_name: "pncp-contracts",
        status: "healthy",
      },
    },
    {
      id: "cc:operational-snapshot:client-acme",
      scope: "client:acme",
      snapshot_kind: "clients",
      generated_at: "2026-08-20T11:45:00.000Z",
      source: src("warmbly", "client-ops", "clients/acme"),
      observed_at: "2026-08-20T11:45:00.000Z",
      freshness_status: FRESH,
      confidence: 0.8,
      payload: {
        schema_version: "control-center.clients-snapshot.v1",
        client_slug: "acme",
        lifecycle: "active",
        display_name: "ACME",
      },
    },
    {
      id: "cc:operational-snapshot:client-other",
      scope: "client:other",
      snapshot_kind: "clients",
      generated_at: "2026-08-20T11:45:00.000Z",
      source: src("warmbly", "client-ops", "clients/other"),
      observed_at: "2026-08-20T11:45:00.000Z",
      freshness_status: FRESH,
      confidence: 0.8,
      payload: {
        schema_version: "control-center.clients-snapshot.v1",
        client_slug: "other",
        lifecycle: "churn_risk",
        display_name: "Other",
        sibling_marker: "client-other-only",
      },
    },
    {
      id: "cc:operational-snapshot:founder-override",
      scope: "company",
      snapshot_kind: "founder-override",
      generated_at: OPERATIONAL_NOW,
      source: src("manual", "founder-override", "attention/override"),
      observed_at: OPERATIONAL_NOW,
      freshness_status: FRESH,
      confidence: 1,
      payload: {
        actor: { kind: "human", id: "founder-local" },
        at: OPERATIONAL_NOW,
        action: "pin",
        target_ids: ["cc:attention-item:overdue-receivable"],
      },
    },
  ];
}

export function representativeOperationalData() {
  return {
    collector_runs: representativeCollectorRuns(),
    source_observations: representativeSourceObservations(),
    operational_snapshots: representativeOperationalSnapshots(),
  };
}
